### ISSUE TITLE
ActiveRecord Dialect Configuration issue

### ISSUE THREAD

**Issue by kpathaka** [castleproject/ActiveRecord#6]
/Hi Team,
I have upgraded Castle.ActiveRecord from 1.0.3.4333 to 3.0.0.1 in my .NET web application with Framework 4.7.  I am facing configuration issue while loading the assembly.
Please see the inner exception: Could not load type NHibernate.Dialect.OracleDialect. Possible cause: no assembly name specified.

**Comment by kpathaka** [comment]
Configuration Details in web.config file,

<activerecord isWeb="true" >
    <config>
      <add key="connection.driver_class" value="NHibernate.Driver.OracleClientDriver"/>
      <add key="dialect" value="NHibernate.Dialect.OracleDialect"/>
      <add key="connection.provider" value="NHibernate.Connection.DriverConnectionProvider"/>
      <add key="connection.connection_string" value="Data Source=connectionDetials;User ID=test;Password=test;"/>
    </config>
  </activerecord>

**Comment by stakx** [comment]
Hi @kpathaka, I'm sure you've noticed (via this project's organization name) that this library is considered deprecated, and thus no longer maintained. Unless you or someone else wants to step up and maintain it, it'll likely remain inactive. 

Have you considered migrating your code away from ActiveRecord?

We could leave this issue open for some more time in case someone wants to chime in and offer a solution for the problem reported. However, you've perhaps also moved on since May. Please let us know whether we can close this or whether you'd like to wait for possible feedback a little longer.

**Comment by kpathaka** [comment]
resolved

**Comment by kpathaka** [comment]
Hi,
Thank you for replying , We have upgraded active record to a latest version
